name: senvx-publish
on:
  push:
    tags:
      - '*'

jobs:
  build_senvx:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64
          - os: macos-latest
            platform: osx-64
          - os: windows-latest
            platform: win-64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.8
          activate-environment: "test"
          channels: conda-forge,defaults,jorgegarciairazabal
      - name: install senv
        shell: bash -l {0}
        run: |
          conda install senv==0.0.0a1 -y
      - name: install senvx virtual env
        shell: bash -l {0}
        run: |
          senv env install

      - name: create installer
        shell: bash -l {0}
        run: |
          senv e run pyinstaller senvx/main.py  -F -n senvx-${{ matrix.platform }} -c

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/senvx*
          asset_name: senvx-${{ matrix.platform }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Publish to pypi and anaconda
        shell: bash -l {0}
        run: |
          senv package publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} -b --build-system poetry -y
          senv package publish -u ${{ secrets.ANACONDA_USERNAME }} -p ${{ secrets.ANACONDA_PASSWORD }} -b --build-system conda -y

