name: senvx-test
on: [ push ]

jobs:
  build_senvx:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,defaults,jorgegarciairazabal
          show-channel-urls: true
          python-version: 3.8
          activate-environment: "test"
      - name: install senv
        shell: bash -l {0}
        run: |
          conda install senv==0.0.0a1 -y

      - name: install senvx virtual env
        shell: bash -l {0}
        run: |
          senv env install

      - name: run tests
        shell: bash -l {0}
        run: |
          senv env run pytest --junit-xml pytest.xml


